- name: set hostname
  ansible.builtin.hostname:
    name: vps.iledevopstest.top
    use: systemd

- name: localhost
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 localhost.localdomain localhost

- name: vps.iledevopstest.top
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 172.105.75.112 vps.iledevopstest.top vps
