- name: install packages
  community.general.pacman:
    update_cache: yes
    name:
      - lxc
      - arch-install-scripts
    state: present

- name: default.conf
  ansible.builtin.copy:
    src: files/default.conf
    dest: /etc/lxc/default.conf
    owner: root
    group: root
    mode: '644'

- name: backups directory
  ansible.builtin.file:
    path: /mnt/storage/backups/lxc
    owner: root
    group: root
    mode: '700'
    state: directory

- name: backup script for lxc mail.iledevopstest.top
  ansible.builtin.copy:
    src: files/lxc-backup-mail-iledevopstest-com.sh
    dest: /root/scripts
    owner: root
    group: root
    mode: '700'

- name: .env-lxc-backups
  ansible.builtin.copy:
    src: files/.env-lxc-backups
    dest: /root/scripts
    owner: root
    group: root
    mode: '600'

- name: add backup script for lxc mail.iledevopstest.top to cron
  ansible.builtin.cron:
    name: lxc mail.iledevopstest.top
    minute: "01"
    hour: "1"
    user: root
    job: "/root/scripts/lxc-backup-mail-ildevopstest-top.sh > /dev/null 2>&1"

- name: ensure lxc mail.iledevopstest.top is enabled at boot
  ansible.builtin.systemd:
    name: lxc@mail.iledevopstest.top
    enabled: yes

- name: backup script for lxc zulip.iledevopstest.top
  ansible.builtin.copy:
    src: files/lxc-backup-zulip-iledevopstest-top.sh
    dest: /root/scripts
    owner: root
    group: root
    mode: '700'

- name: add backup script for lxc zulip.iledevopstest.top to cron
  ansible.builtin.cron:
    name: lxc zulip.iledevopstest.top backup
    minute: "11"
    hour: "1"
    user: root
    job: "/root/scripts/lxc-backup-zulip-iledevopstest-top.sh > /dev/null 2>&1"

- name: ensure lxc zulip.iledevopstest.top is enabled at boot
  ansible.builtin.systemd:
    name: lxc@zulip.iledevopstest.top
    enabled: yes
